services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    environment:
      - OTEL_SERVICE_NAME=rlswarm-fastapi
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/healthz"]
      interval: 30s
      retries: 3

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "55679:55679"  # Prometheus metrics (optional)
    environment:
      - OTEL_LOG_LEVEL=DEBUG
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:4317"]
      interval: 5s
      retries: 5

  swarm-cpu:
    profiles: ["swarm"]
    build:
      context: .
      dockerfile: containerfiles/swarm-node/swarm-cpu.containerfile
    ports:
      - 3000:3000
    volumes:
      - ./user/modal-login:/home/gensyn/rl_swarm/modal-login/temp-data
      - ./user/keys:/home/gensyn/rl_swarm/keys
      - ./user/configs:/home/gensyn/rl_swarm/configs
    environment:
      - HF_TOKEN=${HF_TOKEN}

  swarm-gpu:
    profiles: ["swarm"]
    build:
      context: .
      dockerfile: containerfiles/swarm-node/swarm-gpu.containerfile
    ports:
      - 3000:3000
    volumes:
      - ./user/modal-login:/home/gensyn/rl_swarm/modal-login/temp-data
      - ./user/keys:/home/gensyn/rl_swarm/keys
      - ./user/configs:/home/gensyn/rl_swarm/configs
    environment:
      - HF_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
